### ISSUE TITLE
Is the package updated

### ISSUE THREAD

**Issue by Emaasit** [ramhiser/activelearning#10]
Hello John,
I was searching for a package on active learning when I came across your github repo. I was wondering whether this package is up to date, considering that the last update was in 2012. It also appears that the package is not compartible with R version >3.2.0.

Thanks,
Daniel

**Comment by ramhiser** [comment]
@Emaasit I haven't kept the package up to date. However, the main dependency is `caret`, so that would be the primary package you would want to check compatibility. While I have the goal of updating in the future, I am unable to work on it currently. Pull requests are welcome though. Thank you for your interest.
